# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: timpore
  admin_email: timporecopia@gmail.com
  admin_password: b7mnhmpphe
  domain_name: example.com
  secret_key_base: e363a6dd5911ca511f2030abc1d76ffa9f29d7e4ee3c8c34c7eb245087679f29247d1cf501d123c004b3f32160fcdcdfd4b7d01f5954f3992d4b21040f32c341

test:
  domain_name: example.com 
  secret_key_base: 8a8a378e6111fe3650c938fec4b31ddf9ceb59da4dfcfaddd3d83c16ff5543355893b664b7bc05f7ed4157450aae4546285ca15d4351a7d1da89a710788376c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
